package com.example.dividend.dto.response;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.List;
import java.util.Map;

@Getter
@AllArgsConstructor
public class DividendAutoGenerateResponse {
    private Map<String, Object> confirmed;
    private List<Map<String, Object>> autoGenerated;
}
